steps:
- script: |
    dotnet tool install --global dotnet-ef --version 3.1.3
    cd API
    cd Trustpower.TradingDeals.Web
    dotnet ef migrations script --output $(build.artifactstagingdirectory)\migrations\scripts.sql --idempotent
  displayName: 'Generating idempotent migrations'


- task: PublishBuildArtifacts@1
  displayName: 'Generate migrations artifact'
  inputs:
    artifactName: Migrations
