// this is to be used with vscode extension Rest Client

POST https://tpwapimgmtqa.azure-api.net/queueforwarder/v1/topic/notifications
content-type: application/json
Ocp-Apim-Subscription-Key: abd03cb60af64780825796d63466f7ff

{
    "TrackerId" : "1000",
    "Properties": { "IsEmail": true },
    "MessageBody": "{
    \"EmailTo\": \"joaot@datacom.co.nz\",
    \"EmailFrom\": \"joao.trabbold@trustpower.co.nz\",
    \"Subject\": \"New DealSystem - TEST\",
    \"IsHtml\": true,
    \"Attachments\": [
        {
        \"Name\": \"string\",
        \"Contents\": \"string\",
        \"AttachmentPath\": \"string\"
        }
    ],
    \"Body\": \"
    <html>
        <body>
            <h1>
                TEST
            </h1>
            <p>
                kdjflaskdjflasdkjfasdkjfl
                asdlfjasldkfjalsdkfjalsdkjfalsd
            </p>            
        </body>
    </html>
    \"
    }",
}

